AWSTemplateFormatVersion: 2010-09-09
Description: Infrastructure to set up the build pipeline for the SAM app


Parameters:
  BranchName:
    Description: GitHub branch name
    Type: String
    Default: master
    AllowedPattern: ".+"
  RepositoryName:
    Description: GitHub repository name
    Type: String
    AllowedPattern: ".+"
  GitHubOwner:
    Type: String
    AllowedPattern: ".+"
  GitHubOAuthToken:
    Type: String
    NoEcho: true
    AllowedPattern: ".+"
  ExcludeRegex:
    Description: CloudWatch log group exclude regex
    Type: String
    Default: ".*[cC]loud[tT]rail.*$|^.*ops-aws-[^f].*$|^.*Single.*$|^.*(stg|stage|dev|test|Dev|Test).*$|.*/aws/flowlogs.*"
    AllowedPattern: ".+"
  S3BucketPrefix:
    Description: Prefix of any S3 buckets created through the pipeline (used to set IAM persmissions)
    Type: String
    AllowedPattern: ".+"


Resources:
  CloudFormationTrustRole:    
    Type: AWS::IAM::Role
    Description: Creating service role in IAM for AWS CloudFormation
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - cloudformation.amazonaws.com
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - iam:CreateRole
            - iam:AttachRolePolicy
            - iam:PutRolePolicy
            - iam:PassRole
            - iam:DetachRolePolicy
            - iam:ListRolePolicies
            - iam:GetRole
            - iam:DeleteRolePolicy
            - iam:UpdateRoleDescription
            - iam:ListRoles
            - iam:DeleteRole
            - iam:GetRolePolicy
            - iam:CreateInstanceProfile
            - iam:AddRoleToInstanceProfile
            - iam:DeleteInstanceProfile
            - iam:GetInstanceProfile
            - iam:ListInstanceProfiles
            - iam:ListInstanceProfilesForRole
            - iam:RemoveRoleFromInstanceProfile
            Effect: Allow
            Resource:
            - !Sub "arn:aws:iam::*:role/${AWS::StackName}*"
            - !Sub "arn:aws:iam::*:instance-profile/${AWS::StackName}*"
          - Action:
            - ssm:GetParameters
            - autoscaling:*
            - ec2:*
            - codedeploy:*
            - elasticloadbalancing:*
            Effect: Allow
            Resource: '*'
        PolicyName: !Join
          - '-'
          -  - !Ref 'AWS::StackName'
             - CloudFormationRolePolicy
      RoleName: !Join
        - '-'
        -  - !Ref 'AWS::StackName'
           - CloudFormation


  CodeBuildPolicy:
    Type: AWS::IAM::Policy
    Description: Setting IAM policy for service role for CodeBuild
    Properties:
      PolicyDocument:
        Statement:
        - Action: 
            - iam:ListPolicies
            - iam:GetRole
            - iam:PassRole
            - iam:CreateRole
            - iam:CreatePolicy
            - iam:DeleteRole
            - iam:DetachRole
            - iam:AttachRolePolicy
            - iam:DetachRolePolicy
            - iam:DeleteRolePolicy
            - iam:PutRolePolicy
            - iam:PutGroupPolicy 
            - iam:DeleteGroupPolicy
          Effect: Allow
          Resource: '*'
        - Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          - logs:DescribeMetricFilters
          - logs:FilterLogEvents 
          Effect: Allow
          Resource: '*'
        - Action:
          - cloudformation:*
          Effect: Allow
          Resource: '*'
        - Action:
          - codepipeline:*
          Effect: Allow
          Resource: '*'
        - Action:
          - codebuild:*
          Effect: Allow
          Resource: '*'
        - Action:
          - lambda:ListFunctions
          - lambda:ListLayers
          - lambda:ListEventSourceMappings
          - lambda:GetFunction
          - lambda:GetFunctionConfiguration
          - lambda:CreateFunction
          - lambda:DeleteFunction
          - lambda:CreateLayer
          - lambda:CreateEventSourceMapping
          - lambda:UpdateEventSourceMapping
          - lambda:UpdateFunctionCode
          - lambda:UpdateFunctionConfiguration
          - lambda:AddPermission
          - lambda:RemovePermission
          - lambda:TagResource
          - lambda:UntagResource
          - lambda:ListTags
          - lambda:DeleteFunctionConcurrency
          - lambda:PutFunctionConcurrency
          Effect: Allow
          Resource: '*'
        - Action:
          - lambda:InvokeFunction
          Effect: Allow
          Resource: 
          - !Join
            - ':'
            - - arn:aws:lambda
              - !Ref 'AWS::Region'
              - !Ref 'AWS::AccountId'
              - function:ops-aws-fake-cw-errors-new
        - Action:
          - events:PutRule
          - events:DeleteRule
          - events:RemoveTargets
          - events:DescribeRule
          - events:PutTargets
          Effect: Allow
          Resource: '*'
        - Action:
          - cloudwatch:DescribeAlarms 
          - cloudwatch:DeleteAlarms
          - cloudwatch:PutMetricAlarm 
          - cloudwatch:PutAnomalyDetector
          - cloudwatch:DeleteAnomalyDetector
          - cloudwatch:DeleteAlarms
          - cloudwatch:DeleteAnomalyDetector 
          Effect: Allow
          Resource: '*'
        - Action:
          - budgets:ViewBudget
          - budgets:ModifyBudget
          Effect: Allow
          Resource: '*'
        - Action:
          - securityhub:DescribeHub 
          - securityhub:ListTagsForResource
          Effect: Allow
          Resource: '*'  
        - Action:
          - tag:GetResources
          - tag:GetTagValues
          Effect: Allow
          Resource: '*'  
        - Action:
          - sns:ListTopics
          - sns:CreateTopic
          - sns:Subscribe
          - sns:DeleteTopic
          - sns:GetTopicAttributes
          - sns:SetTopicAttributes
          - sns:ListSubscriptionsByTopic
          - sns:Unsubscribe
          Effect: Allow
          Resource: '*'
        - Action:
          - s3:CreateBucket
          - s3:DeleteBucket
          - s3:PutObject
          - s3:GetObject
          - s3:GetObjectVersion
          - s3:ListObjectsV2
          - s3:PutBucketPolicy
          - s3:PutBucketNotification
          Effect: Allow
          Resource: 
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref 'ArtifactsBucket'
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref 'ArtifactsBucket'
              - /*
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref 'S3BucketPrefix'
              - '*'
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref 'S3BucketPrefix'
              - '*/*'
        - Action:
          - kms:GenerateDataKey*
          - kms:Encrypt
          - kms:Decrypt
          Effect: Allow
          Resource:
          - !Join
            - ':'
            - - arn:aws:kms
              - !Ref 'AWS::Region'
              - !Ref 'AWS::AccountId'
              - !Join
                - /
                - - alias
                  - aws/s3
        - Action:
          - iam:AttachGroupPolicy
          - iam:PutGroupPolicy
          Effect: Allow
          Resource: 
          - !Join
            - ':'
            - - "arn:aws:iam:"
              - !Ref 'AWS::AccountId'
              - "group/ops-aws" 
      PolicyName: !Join
        - '-'
        -  - !Ref 'AWS::StackName'
           - CodeBuildPolicy
      Roles:
      - !Ref 'CodeBuildRole'
      #Groups:
      #- ustif-build-test



  CodeBuildPolicyS3:
    Type: AWS::IAM::Policy
    Description: Setting IAM policy for service role for CodeBuild
    Properties:
      PolicyName: !Join
        - '-'
        -  - !Ref 'AWS::StackName'
           - CodeBuildPolicyS3
      PolicyDocument:
        Statement:
        - Action:
          - s3:GetAccessPoint
          - s3:PutAccountPublicAccessBlock
          - s3:GetAccountPublicAccessBlock
          - s3:ListAllMyBuckets
          - s3:ListAccessPoints
          - s3:ListJobs
          - s3:CreateJob
          - s3:HeadBucket
          Effect: Allow
          Resource: "*" 
        - Action:
          - s3:*
          Effect: Allow
          Resource: 
          - 'arn:aws:s3:::ops-aws*'
          - 'arn:aws:s3:::ops-aws*/*'
      Roles:
      - !Ref 'CodeBuildRole'

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    DependsOn:
    - CodeBuildPolicy
    Properties:
      Artifacts:
#        Location: !Ref 'ArtifactsBucket'
#        Name: 'build-output.zip'
#        NamespaceType: BUILD_ID
#        Packaging: ZIP
#        Path: 'codebuild'
        Type: CODEPIPELINE
      Description: !Join
        - ''
        - - 'CodeBuild Project for '
          - !Ref 'AWS::StackName'
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        ImagePullCredentialsType: CODEBUILD
        EnvironmentVariables:
          - Name: "ARTIFACT_S3_BUCKET"
            Type: PLAINTEXT
            Value: !Ref ArtifactsBucket
          - Name: "BRANCH"
            Type: PLAINTEXT
            Value: !Ref BranchName
          - Name: "STACK_NAME"
            Type: PLAINTEXT
            Value: !Ref 'AWS::StackName'
          - Name: "EXCLUDE_REGEX"
            Type: PLAINTEXT
            Value: !Ref 'ExcludeRegex'
      Name: !Join 
        - "-" 
        - - !Ref 'AWS::StackName'
      ServiceRole: !Ref 'CodeBuildRole'
      Source:
        Type: CODEPIPELINE
#        Auth:
#          Resource: !Ref CodeBuildSourceCredential
#          Type: OAUTH
#        Location: "https://github.com/i2dwhadmn/ops-aws-config-basic"
        BuildSpec: 'buildspec.yml'

  CodeBuildEndToEndTestProject:
    Type: AWS::CodeBuild::Project
    DependsOn:
    - CodeBuildPolicy
    Properties:
      Artifacts:
#        Location: !Ref 'ArtifactsBucket'
#        Name: 'build-output.zip'
#        NamespaceType: BUILD_ID
#        Packaging: ZIP
#        Path: 'codebuild'
        Type: CODEPIPELINE
      Description: !Join
        - ''
        - - 'CodeBuild End to End Test Project for '
          - !Ref 'AWS::StackName'
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        ImagePullCredentialsType: CODEBUILD
        EnvironmentVariables:
          - Name: "ARTIFACT_S3_BUCKET"
            Type: PLAINTEXT
            Value: !Ref ArtifactsBucket
          - Name: "BRANCH"
            Type: PLAINTEXT
            Value: !Ref BranchName
          - Name: "STACK_NAME"
            Type: PLAINTEXT
            Value: !Ref 'AWS::StackName'
          - Name: "EXCLUDE_REGEX"
            Type: PLAINTEXT
            Value: !Ref 'ExcludeRegex'
      Name: !Join 
        - "-" 
        - - !Ref 'AWS::StackName'
          - "EndToEndTest"
      ServiceRole: !Ref 'CodeBuildRole'
      Source:
        Type: CODEPIPELINE
#        Auth:
#          Resource: !Ref CodeBuildSourceCredential
#          Type: OAUTH
#        Location: "https://github.com/i2dwhadmn/ops-aws-config-basic"
        BuildSpec: 'buildspec_end_to_end_test.yml'

  CodeBuildRole:
    Type: AWS::IAM::Role
    Description: Creating service role in IAM for AWS CodeBuild
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
      Path: /
      RoleName: !Join
        - '-'
        - - !Ref 'AWS::StackName'
          - CodeBuild



  CodePipelineTrustRole:
    Type: AWS::IAM::Role
    Description: Creating service role in IAM for AWS CodePipeline
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - codepipeline.amazonaws.com
          Sid: 1
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - s3:GetObject
            - s3:GetObjectVersion
            - s3:GetBucketVersioning
            - s3:PutObject
            - s3:CreateBucket
            - s3:DeleteBucket
            Effect: Allow
            Resource:
            - !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref 'ArtifactsBucket'
            - !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref 'ArtifactsBucket'
                - /*
            - 'arn:aws:s3:::ops-aws*'
            - 'arn:aws:s3:::ops-aws*/*'
          - Action:
            - codecommit:CancelUploadArchive
            - codecommit:GetBranch
            - codecommit:GetCommit
            - codecommit:GetUploadArchiveStatus
            - codecommit:UploadArchive
            Effect: Allow
            Resource:
            - !Join
              - ':'
              - - arn
                - aws
                - codecommit
                - !Ref 'AWS::Region'
                - !Ref 'AWS::AccountId'
                - !Ref RepositoryName
          - Action:
            - codebuild:StartBuild
            - codebuild:BatchGetBuilds
            - codebuild:StopBuild
            - codebuild:BatchGetProjects
            Effect: Allow
            Resource:
            - !GetAtt 'CodeBuildProject.Arn'
            - !GetAtt 'CodeBuildEndToEndTestProject.Arn'
          - Action:
            - cloudformation:DescribeStacks
            - cloudformation:DescribeChangeSet
            - cloudformation:CreateChangeSet
            - cloudformation:DeleteChangeSet
            - cloudformation:ExecuteChangeSet
            Effect: Allow
            Resource:
            - !Join
              - ':'
              - - arn
                - aws
                - cloudformation
                - !Ref 'AWS::Region'
                - !Ref 'AWS::AccountId'
                - !Join
                  - /
                  - - stack
                    - !Join
                      - '-'
                      -  - !Ref 'AWS::StackName'
                         - '*'
          - Action:
            - iam:PassRole
            Effect: Allow
            Resource:
            - !GetAtt
              - CloudFormationTrustRole
              - Arn
        PolicyName: !Join
          - '-'
          - - !Ref 'AWS::StackName'
            - CodePipelineRolePolicy
      RoleName: !Join
        - '-'
        - - !Ref 'AWS::StackName'
          - CodePipeline


  ReleasePipeline:
    Type: AWS::CodePipeline::Pipeline
    DependsOn:
    - CodePipelineTrustRole
    - ArtifactsBucket
    - CodeBuildProject
    - CodeBuildEndToEndTestProject
    - CloudFormationTrustRole
    Description: Creating a deployment pipeline for your project in AWS CodePipeline
    Properties:
      ArtifactStore:
        Location: !Ref 'ArtifactsBucket'
        Type: S3
      Name: !Join
          - '-'
          -  - !Ref 'AWS::StackName'
             - "sam-cli"
      RoleArn: !GetAtt
      - CodePipelineTrustRole
      - Arn
      Stages:
      - Name: Source
        Actions:
          - Name: SourceAction
            ActionTypeId:
              Category: Source
              Owner: ThirdParty
              Version: 1
              Provider: GitHub
            OutputArtifacts:
            - Name: !Join
              - '-'
              - - !Ref 'AWS::StackName'
                - Source
            Configuration:
              Owner: !Ref GitHubOwner
              Repo: !Ref RepositoryName
              Branch: !Ref BranchName
              OAuthToken: !Ref GitHubOAuthToken
              PollForSourceChanges: True # Ideally, this would be false and triggered by a webhook, but I'm having trouble getting that to create  consistently upon build.
            RunOrder: 1
      - Name: Build
        Actions:
        - ActionTypeId:
            Category: Build
            Owner: AWS
            Provider: CodeBuild
            Version: 1
          Configuration:
            ProjectName: !Ref 'AWS::StackName'
          InputArtifacts:
          - Name: !Join
            - '-'
            - - !Ref 'AWS::StackName'
              - Source
          Name: Build
          OutputArtifacts:
          - Name: !Join
            - '-'
            - - !Ref 'AWS::StackName'
              - Build
          RunOrder: 1


  ArtifactBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Description: Setting Amazon S3 bucket policy for AWS CodePipeline access
    Properties:
      Bucket: !Ref 'ArtifactsBucket'
      PolicyDocument:
        Id: SSEAndSSLPolicy
        Statement:
        - Action:
          - s3:GetObject
          - s3:GetObjectVersion
          - s3:GetBucketVersioning
          Condition:
            Bool:
              aws:SecureTransport: false
          Effect: Allow
          Principal:
            AWS:
            - !GetAtt
              - CodePipelineTrustRole
              - Arn
            - !GetAtt
              - CodeBuildRole
              - Arn
            - !GetAtt
              - CloudFormationTrustRole
              - Arn
          Resource:
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref 'ArtifactsBucket'
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref 'ArtifactsBucket'
              - /*
          Sid: WhitelistedGet
        - Action:
          - s3:PutObject
          Effect: Allow
          Principal:
            AWS:
            - !GetAtt
              - CodePipelineTrustRole
              - Arn
            - !GetAtt
              - CodeBuildRole
              - Arn
          Resource:
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref 'ArtifactsBucket'
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref 'ArtifactsBucket'
              - /*
          Sid: WhitelistedPut
        Version: 2012-10-17


  ArtifactsBucket:
    Type: AWS::S3::Bucket    
    DeletionPolicy: Delete
    Description: Creating Amazon S3 bucket for AWS CodePipeline and CodeBuild artifacts
    Properties:
      Tags:
      - Key: Name
        Value: !Join
        - '-'
        - - !Ref 'AWS::StackName'
          - Arts
      - Key: Type
        Value: ops-aws
      VersioningConfiguration:
        Status: Enabled


Outputs:
  ReleasePipelineName:
    Description: Name of the created code pipeline
    Value: !Ref ReleasePipeline
  S3Artifacts:
    Description: Name of the S3 bucket for source artifacts
    Value: !Ref ArtifactsBucket


